stages:
  - compile
  - test

language: c

compiler:
  - gcc

jobs:
  include:
    - stage: compile
      name: "All"
      script: cmake . && make

cache:
  directories:
  - IsoLib/HM/build/linux/app/TAppDecoder/objects/
  - IsoLib/HM/build/linux/app/TAppDecoderAnalyser/objects/
  - IsoLib/HM/build/linux/app/TAppEncoder/objects/
  - IsoLib/HM/build/linux/lib/TAppCommon/objects/
  - IsoLib/HM/build/linux/lib/TLibCommon/objects/
  - IsoLib/HM/build/linux/lib/TLibDecoder/objects/
  - IsoLib/HM/build/linux/lib/TLibDecoderAnalyser/objects/
  - IsoLib/HM/build/linux/lib/TLibEncoder/objects/
  - IsoLib/HM/build/linux/lib/TLibVideoIO/objects/
  - IsoLib/HM/build/linux/utils/annexBbytecount/objects/
  - IsoLib/HM/build/linux/utils/convert_NtoMbit_YCbCr/objects/
