all:
	$(MAKE) -C ../libisomediafile/linux/libisomediafile
	$(MAKE) -C ../audio_example/linux
	$(MAKE) -C ../drc_in_isom/linux
	$(MAKE) -C ../favs_example/linux
	$(MAKE) -C ../hevc_extractors/linux
	$(MAKE) -C ../ipmp_example/linux
	$(MAKE) -C ../isoiff_tool/linux/isoiff
	$(MAKE) -C ../isoiff_tool/linux/isoiff_tool
